const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.Anchor,
		C3.Plugins.TiledBg,
		C3.Behaviors.Pin,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Plugins.Audio,
		C3.Behaviors.Platform,
		C3.Behaviors.bound,
		C3.Behaviors.scrollto,
		C3.Plugins.Text,
		C3.Behaviors.jumpthru,
		C3.Behaviors.Sin,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Keyboard.Cnds.OnKeyReleased,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Behaviors.Platform.Cnds.IsFalling,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Audio.Acts.Play,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Plugins.System.Cnds.Else,
		C3.ScriptsInEvents.FolhaFase1_Event12_Act2,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Cnds.IsMirrored,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.ScriptsInEvents.FolhaFase2_Event11_Act2,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Mouse.Cnds.OnObjectClicked
	];
};
self.C3_JsPropNameTable = [
	{Sólido: 0},
	{ChãoMeio: 0},
	{ChãoBeiradaEsquerda: 0},
	{ChãoPenhascoEsquerda: 0},
	{LuzPostes: 0},
	{Âncora: 0},
	{Coração: 0},
	{PlacaFrente: 0},
	{GraminhaCenário: 0},
	{ChãoInterno: 0},
	{ChãoVoltinha1: 0},
	{Arvore: 0},
	{CenárioCerquinha: 0},
	{ChãoPenhascoDireita: 0},
	{ChãoBeiradaDireita: 0},
	{Osso: 0},
	{FundoMarrom: 0},
	{Arvore2: 0},
	{ChãoFlutuante1: 0},
	{ChãoFlutuante2: 0},
	{ChãoFlutuante3: 0},
	{Casa: 0},
	{ParedeCasa: 0},
	{TelhadoCasa: 0},
	{PosteDeLuz: 0},
	{PlacaMorte: 0},
	{Fixar: 0},
	{Ania: 0},
	{Teclado: 0},
	{Mouse: 0},
	{PoçoCenário: 0},
	{Matinho: 0},
	{PlacaBaixo: 0},
	{PlacaCima: 0},
	{Toco: 0},
	{Arvore3: 0},
	{Áudio: 0},
	{Vagalumes: 0},
	{FundoEstrelas: 0},
	{FundoNuvensClaras: 0},
	{NuvensEscuras: 0},
	{FundoEstrelasGameOver: 0},
	{FundoNuvensCGameOver: 0},
	{NuvensEGameOver: 0},
	{Fundo: 0},
	{LuaGameOver: 0},
	{ArvoresGameOver: 0},
	{ArvoreGameOver2: 0},
	{GameOver: 0},
	{Lua: 0},
	{ChãoMovelD: 0},
	{ChãoVoltinha2: 0},
	{ChãoMovelE: 0},
	{ChãoPular: 0},
	{MusguinhoSobeDesce: 0},
	{Carroça: 0},
	{PlacaAtenção: 0},
	{PedraMusgo: 0},
	{Balde: 0},
	{PedraRio: 0},
	{Chave: 0},
	{Plataforma: 0},
	{RestritoAoLayout: 0},
	{Carie: 0},
	{Marcador: 0},
	{CentrarEm: 0},
	{Colisão: 0},
	{TxtVida: 0},
	{Direção: 0},
	{Fadinha: 0},
	{PularAtravés: 0},
	{ChãoPularAtraves: 0},
	{ChãoMeioPular: 0},
	{ChãoPularDireita: 0},
	{PenhascoPularAtraves: 0},
	{ChãoDentroPular: 0},
	{PenhascoPulaRdIREITA: 0},
	{Estátua: 0},
	{No: 0},
	{PlanoDeFundoEmBlocos: 0},
	{Portal: 0},
	{Lado: 0},
	{Boos: 0},
	{TelaPlayGame: 0},
	{Playbutton: 0},
	{Backbutton: 0},
	{Dente: 0},
	{TelaPlayAgain: 0},
	{Sprite2: 0},
	{Sprite: 0},
	{Espinhos: 0},
	{Baú: 0},
	{Sprite4: 0},
	{AparecerDente: 0},
	{Sprite3: 0},
	{Agua: 0},
	{Sprite5: 0},
	{pesca: 0},
	{DeckBase: 0},
	{Deck: 0},
	{Point: 0},
	{CenárioPeixes: 0},
	{Senóide: 0},
	{ChãoMovel: 0},
	{ChãoMovel2: 0},
	{PointStar: 0},
	{vidas: 0}
];

self.InstanceType = {
	ChãoMeio: class extends self.ISpriteInstance {},
	ChãoBeiradaEsquerda: class extends self.ISpriteInstance {},
	ChãoPenhascoEsquerda: class extends self.ISpriteInstance {},
	LuzPostes: class extends self.ISpriteInstance {},
	Coração: class extends self.ISpriteInstance {},
	PlacaFrente: class extends self.ISpriteInstance {},
	GraminhaCenário: class extends self.ISpriteInstance {},
	ChãoInterno: class extends self.ISpriteInstance {},
	ChãoVoltinha1: class extends self.ISpriteInstance {},
	Arvore: class extends self.ISpriteInstance {},
	CenárioCerquinha: class extends self.ISpriteInstance {},
	ChãoPenhascoDireita: class extends self.ISpriteInstance {},
	ChãoBeiradaDireita: class extends self.ISpriteInstance {},
	Osso: class extends self.ISpriteInstance {},
	FundoMarrom: class extends self.ITiledBackgroundInstance {},
	Arvore2: class extends self.ISpriteInstance {},
	ChãoFlutuante1: class extends self.ISpriteInstance {},
	ChãoFlutuante2: class extends self.ISpriteInstance {},
	ChãoFlutuante3: class extends self.ISpriteInstance {},
	Casa: class extends self.ISpriteInstance {},
	ParedeCasa: class extends self.ISpriteInstance {},
	TelhadoCasa: class extends self.ISpriteInstance {},
	PosteDeLuz: class extends self.ISpriteInstance {},
	PlacaMorte: class extends self.ISpriteInstance {},
	Ania: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	PoçoCenário: class extends self.ISpriteInstance {},
	Matinho: class extends self.ISpriteInstance {},
	PlacaBaixo: class extends self.ISpriteInstance {},
	PlacaCima: class extends self.ISpriteInstance {},
	Toco: class extends self.ISpriteInstance {},
	Arvore3: class extends self.ISpriteInstance {},
	Áudio: class extends self.IInstance {},
	Vagalumes: class extends self.ISpriteInstance {},
	FundoEstrelas: class extends self.ISpriteInstance {},
	FundoNuvensClaras: class extends self.ISpriteInstance {},
	NuvensEscuras: class extends self.ISpriteInstance {},
	FundoEstrelasGameOver: class extends self.ITiledBackgroundInstance {},
	FundoNuvensCGameOver: class extends self.ITiledBackgroundInstance {},
	NuvensEGameOver: class extends self.ITiledBackgroundInstance {},
	Fundo: class extends self.ITiledBackgroundInstance {},
	LuaGameOver: class extends self.ITiledBackgroundInstance {},
	ArvoresGameOver: class extends self.ISpriteInstance {},
	ArvoreGameOver2: class extends self.ISpriteInstance {},
	GameOver: class extends self.ISpriteInstance {},
	Lua: class extends self.ITiledBackgroundInstance {},
	ChãoMovelD: class extends self.ISpriteInstance {},
	ChãoVoltinha2: class extends self.ISpriteInstance {},
	ChãoMovelE: class extends self.ISpriteInstance {},
	ChãoPular: class extends self.ISpriteInstance {},
	MusguinhoSobeDesce: class extends self.ISpriteInstance {},
	Carroça: class extends self.ISpriteInstance {},
	PlacaAtenção: class extends self.ISpriteInstance {},
	PedraMusgo: class extends self.ISpriteInstance {},
	Balde: class extends self.ISpriteInstance {},
	PedraRio: class extends self.ISpriteInstance {},
	Chave: class extends self.ISpriteInstance {},
	Carie: class extends self.ISpriteInstance {},
	Marcador: class extends self.ISpriteInstance {},
	Colisão: class extends self.ISpriteInstance {},
	TxtVida: class extends self.ITextInstance {},
	Fadinha: class extends self.ISpriteInstance {},
	ChãoPularAtraves: class extends self.ISpriteInstance {},
	ChãoMeioPular: class extends self.ISpriteInstance {},
	ChãoPularDireita: class extends self.ISpriteInstance {},
	PenhascoPularAtraves: class extends self.ISpriteInstance {},
	ChãoDentroPular: class extends self.ISpriteInstance {},
	PenhascoPulaRdIREITA: class extends self.ISpriteInstance {},
	Estátua: class extends self.ISpriteInstance {},
	No: class extends self.ITextInstance {},
	PlanoDeFundoEmBlocos: class extends self.ITiledBackgroundInstance {},
	Portal: class extends self.ISpriteInstance {},
	Boos: class extends self.ISpriteInstance {},
	TelaPlayGame: class extends self.ISpriteInstance {},
	Playbutton: class extends self.ISpriteInstance {},
	Backbutton: class extends self.ISpriteInstance {},
	Dente: class extends self.ISpriteInstance {},
	TelaPlayAgain: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Espinhos: class extends self.ISpriteInstance {},
	Baú: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	AparecerDente: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Agua: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	pesca: class extends self.ISpriteInstance {},
	DeckBase: class extends self.ISpriteInstance {},
	Deck: class extends self.ISpriteInstance {},
	Point: class extends self.ISpriteInstance {},
	CenárioPeixes: class extends self.ISpriteInstance {},
	ChãoMovel: class extends self.ISpriteInstance {},
	ChãoMovel2: class extends self.ISpriteInstance {},
	PointStar: class extends self.ISpriteInstance {}
}